Develop
cavesdev/skt-webshop pull request #2
Opened 2024-10-24 20:15 UTC by cavesdev

2024-10-25 00:51 UTC, cavesdev commented on common-library/src/main/java/com/encora/common/model/Product.java
> +public class Product {
Great recommendation

2024-10-25 01:00 UTC, foji9315 commented on common-library/src/main/java/com/encora/common/model/Product.java
> +    public Product(Integer id, String name, String description, Double price) {
FYI: lombok also provide constructor with and without arguments.

2024-10-25 01:00 UTC, foji9315 commented on management-app/pom.xml
> +      <artifactId>spring-boot-starter-amqp</artifactId>
what version is being used?

2024-10-25 01:01 UTC, foji9315 commented on management-app/src/main/java/com/encora/ManagementApp.java
> +        return builder.sources(ManagementApp.class);
not sure, but is this Builder required?

2024-10-25 17:00 UTC, EdwinFajardoBarrera requested changes

2024-10-25 17:00 UTC, EdwinFajardoBarrera commented on management-app/pom.xml
> +    <dependency>
Define and extract versions to a <properties> seccion

2024-10-25 17:00 UTC, EdwinFajardoBarrera commented on management-app/src/main/java/com/encora/controller/ProductController.java
> +        model.addAttribute("products", products);
We recommend to extract strings as much as possible to constants. In this case, "products" or endpoint names "/saveProduct" we use to create constants so we can re-use them latter

2024-10-25 17:00 UTC, EdwinFajardoBarrera commented on management-app/src/main/resources/application.properties
> +spring.mvc.view.prefix=/WEB-INF/views/
Consider using YML instead of .properties file, I think it is more maintainable and this is how we manage configurations

2024-10-25 17:00 UTC, EdwinFajardoBarrera commented on management-app/src/main/webapp/WEB-INF/views/listProducts.jsp
> +                        <td>${product.name}</td>
Use c:out tag instead JSP default printing:

https://stackoverflow.com/a/18309775

2024-10-25 17:00 UTC, EdwinFajardoBarrera commented on pom.xml
> +      <version>1.18.34</version>
Extract versions

2024-10-25 19:36 UTC, cavesdev commented on management-app/src/main/java/com/encora/ManagementApp.java
> +        return builder.sources(ManagementApp.class);
Only required to run Management app as a standalone app. It was for testing, I can remove it

2024-10-26 00:21 UTC, EdwinFajardoBarrera approved these changes

2024-10-28 17:29 UTC, merged